// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	model "scheduler-service/pkg/model"

	mock "github.com/stretchr/testify/mock"

	websocket "github.com/gorilla/websocket"
)

// StatusService is an autogenerated mock type for the StatusService type
type StatusService struct {
	mock.Mock
}

// HandleNewConnection provides a mock function with given fields: c
func (_m *StatusService) HandleNewConnection(c *websocket.Conn) {
	_m.Called(c)
}

// UpdateJobStatus provides a mock function with given fields: job
func (_m *StatusService) UpdateJobStatus(job *model.Status) {
	_m.Called(job)
}

// NewStatusService creates a new instance of StatusService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStatusService(t interface {
	mock.TestingT
	Cleanup(func())
}) *StatusService {
	mock := &StatusService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
